spring:
  profiles:
    active: DEV, KEY

  jackson:
    time-zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true